import { Geist, Geist_Mono } from "next/font/google";
import { Providers } from "./components/sectionProviders/providers";
import { Toaster } from "react-hot-toast";
import Script from "next/script";
import "./globals.css";





const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
        <Providers>
          <main className="max-w-[1200px] mx-auto p-4">
            {children}
            <Toaster />
            <Script src="https://checkout.razorpay.com/v1/checkout.js" strategy="lazyOnload" />
          </main>
        </Providers>
      </body>
    </html>
  );
}

